version: "3.9"
services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "9080:8080"
    environment: 
      BASE_URL: /swagger
      API_URL: http://localhost:8080/test/v1.0/swagger
  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: dummy
      POSTGRES_DB: services
      TZ: UTC
      PGTZ: UTC
  test:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
